version: "2.1"

services:
  # Backup
  backup:
    container_name: backup
    image: offen/docker-volume-backup:latest
    restart: always
    env_file: ./backup.env
    volumes:
      - ${VOLUME_DIR}/pihole/pihole:/backup/pihole/pihole:ro
      - ${VOLUME_DIR}/pihole/dnsmasq.d:/backup/pihole/dnsmasq.d:ro
      - ${VOLUME_DIR}/unifi:/backup/unifi:ro
      - ${VOLUME_DIR}/homebridge:/backup/homebridge:ro
      # Mounting the Docker socket allows the script to stop and restart
      # the container during backup. You can omit this if you don't want
      # to stop the container
      - /var/run/docker.sock:/var/run/docker.sock:ro
    dns:
      - 9.9.9.9
      - 1.0.0.1

  # DNS over HTTPS
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared
    networks:
      pihole_net:
        ipv4_address: 192.168.0.2
    restart: unless-stopped

  # DNS Filtering
  pihole:
    container_name: pihole
    image: pihole/pihole
    hostname: pi.hole
    env_file: .env
    environment:
      - TZ=America/Chicago
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
      - DNS1=192.168.0.2#5054
      - DNS2=9.9.9.9
      - IPv6=false
      - DNSSEC=true
      - ServerIP=${SERVER_IP}
    volumes:
      - ${VOLUME_DIR}/pihole/pihole:/etc/pihole
      - ${VOLUME_DIR}/pihole/dnsmasq.d:/etc/dnsmasq.d
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 443:443/tcp
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.0.0.1
    hostname: pihole
    depends_on: [cloudflared]
    networks:
      pihole_net:
        ipv4_address: 192.168.0.3
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=true

  # Unifi Controller for Switch and AP
  unifi:
    container_name: unifi
    image: ghcr.io/linuxserver/unifi-controller
    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${VOLUME_DIR}/unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    dns:
      - 9.9.9.9
      - 1.0.0.1
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=true

  # Let me connect to my Kasa devices from Apple Homekit
  homebridge:
    container_name: homebridge
    image: oznu/homebridge:latest
    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=4033
      - TZ=America/Chicago
    volumes:
      - ${VOLUME_DIR}/homebridge:/homebridge
    network_mode: host
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=true

# Allow pihole to connect to cloudflared (DNS over HTTPS)
networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/29
